"""Mixes the raw TTS speech WAVs (generated by generate_fixtures.ps1, under _raw/) with
synthetic pink noise at controlled SNRs, and writes the final committed fixtures +
manifest.json that tests/test_real_audio_fixtures.py loads.

HONESTY NOTE (matches the framing already established for this feature): the noise here
is synthetically generated pink noise, not a real recording of hospital/office ambience
-- no such recording exists in this repo, and none is fabricated-and-mislabeled as real.
It's still a meaningful step up from the existing synthetic-tone fixtures in
test_models_integration.py, because the underlying signal is real human speech (via SAPI
TTS), not a sine tone -- this is what lets the new tests assert something the tone-based
fixtures structurally can't: does VAD actually track natural speech/silence boundaries,
and does the denoiser measurably improve SNR against a *known* clean reference.

Usage: python mix_snr.py   (run from this directory, or anywhere -- paths are relative to
this script's own location, not the caller's cwd)

Dependencies: numpy only (already a transitive dependency of the real service; this
script itself never imports torch/deepfilternet/onnxruntime).
"""

from __future__ import annotations

import json
import wave
from pathlib import Path

import numpy as np

SCRIPT_DIR = Path(__file__).parent
RAW_DIR = SCRIPT_DIR / "_raw"
SAMPLE_RATE = 16000
FRAME_MS = 20

# condition -> target SNR in dB, or None for the clean (noise-free) pass-through.
CONDITIONS: dict[str, float | None] = {
    "clean": None,
    "snr10": 10.0,
    "snr0": 0.0,
}


def read_wav_int16(path: Path) -> np.ndarray:
    with wave.open(str(path), "rb") as wf:
        assert wf.getframerate() == SAMPLE_RATE, f"{path} is not {SAMPLE_RATE}Hz"
        assert wf.getnchannels() == 1, f"{path} is not mono"
        assert wf.getsampwidth() == 2, f"{path} is not 16-bit PCM"
        raw = wf.readframes(wf.getnframes())
    return np.frombuffer(raw, dtype=np.int16).copy()


def write_wav_int16(path: Path, samples: np.ndarray) -> None:
    with wave.open(str(path), "wb") as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(SAMPLE_RATE)
        wf.writeframes(samples.astype(np.int16).tobytes())


def detect_speech_region(clean: np.ndarray) -> tuple[int, int]:
    """Energy-threshold speech-region detection on the CLEAN (noise-free) signal --
    reliable without noise present, unlike trying to do this on a noisy mix. Frame-level
    (20ms), not sample-level, since that's the granularity the actual VAD/denoise
    pipeline and the tests operate at.
    """
    frame_len = SAMPLE_RATE * FRAME_MS // 1000
    n_frames = len(clean) // frame_len
    energies = np.array(
        [
            np.sqrt(np.mean(clean[i * frame_len : (i + 1) * frame_len].astype(np.float64) ** 2))
            for i in range(n_frames)
        ]
    )
    if energies.max() == 0:
        return 0, len(clean)
    active = np.where(energies > energies.max() * 0.1)[0]
    if len(active) == 0:
        return 0, len(clean)
    start_sample = int(active[0]) * frame_len
    end_sample = min(len(clean), (int(active[-1]) + 1) * frame_len)
    return start_sample, end_sample


def pink_noise(n_samples: int, rng: np.random.Generator) -> np.ndarray:
    """Paul Kellet's 'economy' pink-noise filter over white noise -- a standard, simple,
    deterministic (given a seeded rng) approximation of 1/f noise, used here as a
    generic stand-in for broadband office/HVAC-style background noise. Returned
    normalized to peak amplitude 1.0 (float64); callers scale it to hit a target SNR.
    """
    white = rng.normal(0, 1, n_samples)
    b0 = b1 = b2 = 0.0
    pink = np.zeros(n_samples)
    for i in range(n_samples):
        b0 = 0.99765 * b0 + white[i] * 0.0990460
        b1 = 0.96300 * b1 + white[i] * 0.2965164
        b2 = 0.57000 * b2 + white[i] * 1.0526913
        pink[i] = b0 + b1 + b2 + white[i] * 0.1848
    peak = np.max(np.abs(pink))
    return pink / peak if peak > 0 else pink


def mix_at_snr(clean: np.ndarray, speech_start: int, speech_end: int, target_db: float, rng: np.random.Generator) -> np.ndarray:
    """Scales synthetic pink noise so the mix hits target_db SNR, measured against the
    clean signal's RMS *within its known speech region* (not the whole clip, which
    would be diluted by silence padding and not reflect a meaningful "speech vs noise"
    ratio). Noise is added across the WHOLE clip (silence portions too -- realistic:
    background noise doesn't pause when the speaker does), so the same scale factor
    also determines the effective SNR during the silence margins.

    Scaling both signal and noise's relative levels by a single derived `scale` factor
    (never touching the clean signal itself) means the SNR is exact by construction --
    the only approximation is the sample-based RMS estimate itself, not the math.
    """
    clean_f = clean.astype(np.float64)
    speech_region = clean_f[speech_start:speech_end]
    rms_clean = float(np.sqrt(np.mean(speech_region**2)))

    noise = pink_noise(len(clean_f), rng)
    rms_noise = float(np.sqrt(np.mean(noise**2)))

    # target_rms_noise is derived from rms_clean, which is already in int16 units (the
    # clean signal was never normalized) -- so scale converts `noise` (peak-normalized
    # to 1.0 by pink_noise()) directly into int16 units at that target RMS. No further
    # /32768 or *32768 conversion belongs here; scaled_noise is already on the same
    # scale as clean_f.
    target_rms_noise = rms_clean / (10 ** (target_db / 20))
    scale = target_rms_noise / rms_noise
    scaled_noise = noise * scale

    mixed = clean_f + scaled_noise
    peak = np.max(np.abs(mixed))
    if peak > 0.98 * 32768:
        mixed = mixed / peak * 0.98 * 32768
    return mixed.clip(-32768, 32767).astype(np.int16)


def main() -> None:
    raw_files = sorted(RAW_DIR.glob("*.wav"))
    if not raw_files:
        raise SystemExit(f"No raw fixtures found in {RAW_DIR} -- run generate_fixtures.ps1 first")

    manifest = []
    for raw_path in raw_files:
        phrase_id = raw_path.stem
        clean = read_wav_int16(raw_path)
        speech_start, speech_end = detect_speech_region(clean)
        rng = np.random.default_rng(hash(phrase_id) & 0xFFFFFFFF)

        clean_out_name = f"{phrase_id}-clean.wav"
        write_wav_int16(SCRIPT_DIR / clean_out_name, clean)
        manifest.append(
            {
                "file": clean_out_name,
                "phraseId": phrase_id,
                "condition": "clean",
                "speechStartMs": round(speech_start / SAMPLE_RATE * 1000),
                "speechEndMs": round(speech_end / SAMPLE_RATE * 1000),
                "cleanReferenceFile": None,
            }
        )

        for condition, target_db in CONDITIONS.items():
            if target_db is None:
                continue
            mixed = mix_at_snr(clean, speech_start, speech_end, target_db, rng)
            out_name = f"{phrase_id}-{condition}.wav"
            write_wav_int16(SCRIPT_DIR / out_name, mixed)
            manifest.append(
                {
                    "file": out_name,
                    "phraseId": phrase_id,
                    "condition": condition,
                    "speechStartMs": round(speech_start / SAMPLE_RATE * 1000),
                    "speechEndMs": round(speech_end / SAMPLE_RATE * 1000),
                    "cleanReferenceFile": clean_out_name,
                }
            )
        print(f"{phrase_id}: speech region {speech_start / SAMPLE_RATE:.2f}s - {speech_end / SAMPLE_RATE:.2f}s")

    manifest_path = SCRIPT_DIR / "manifest.json"
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n")
    print(f"wrote {manifest_path} ({len(manifest)} fixtures)")


if __name__ == "__main__":
    main()
